### ISSUE TITLE
Addition for time format converter from 12 hour to 24 hour format

### ISSUE THREAD

**Issue by AvinashSubhash** [aravindvnair99/Algorithms#7]
Hey, Can I collaborate in your repository?

**Comment by aravindvnair99** [comment]
> Hey, Can I collaborate in your repository?

@AvinashSubhash Yes, you may.

**Comment by prm1999** [comment]
I had contributed  on your repo
review the pull request

**Comment by aravindvnair99** [comment]
> I had contributed on your repo
> review the pull request

@prm1999 Please be patient and comment only in your issue or pull request. Not here.

**Comment by aravindvnair99** [comment]
@AvinashSubhash Added in ee0cad0
