### ISSUE TITLE
can i create a new pull request?

### ISSUE THREAD

**Issue by Ashlin21dev** [aravindvnair99/Algorithms#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aravindvnair99** [comment]
@Ashlin21dev Yes, you sure can. Feel free to create an issue on what you want to do and then send in a pull request for the same.

**Comment by Ashlin21dev** [comment]
as i am new to this platform, it will take me some time to get used to it,so plesase dont get offended sir!

**Comment by aravindvnair99** [comment]
> as i am new to this platform, it will take me some time to get used to it,so plesase dont get offended sir!

@Ashlin21dev No issues, feel free to ask for help. Here are some links to help you:

- [Git Handbook | GitHub Guides](https://guides.github.com/introduction/git-handbook/)
- [Introduction to Git and GitHub by Google on Coursera](https://www.coursera.org/learn/introduction-git-github)
- [Hello World | GitHub Guides](https://guides.github.com/activities/hello-world/)
- [GitHub Guides](https://guides.github.com/)

**Comment by Ashlin21dev** [comment]
thank you sir, btw am thinking of creating a new pull request and i wonder whether this pull request will be considered for the hacktoberfest?
this will be a useful python code contribution!!

**Comment by Ashlin21dev** [comment]
did anybody review my code yet!?

**Comment by Ashlin21dev** [comment]
can you review and accept my rain prediction code toO!!

**Comment by aravindvnair99** [comment]
@Ashlin21dev Closing this issue due to the inactivity of PR. Feel free to resend PR after making necessary changes.
